export * from './Layout'
export * from './MovieCard'
export * from './Navbar'
export * from './Badge'
export * from './Button'
export * from './movieModals'
export * from './FilterBar'
export * from './Sidebar'
export * from './Seo'

export { default as Layout } from './Layout'
export { default as MovieCard } from './MovieCard'
export { default as Navbar } from './Navbar'
export { default as CustomBadge } from './Badge'
export { default as CustomButton } from './Button'
export { default as FilterBar } from './FilterBar'
export { default as Sidebar } from './Sidebar'
export { default as Seo } from './Seo'
